export const NAV_ROUTE: Array<any> = [


  {
    id: 3,
    idModule: 0,
    readWrite: 0,
    routeDescription: 'Demandes d\'urgence',
    routeLink: '/help_request',
    routeModule: [1],
    routeTitle: 'Demandes d\'urgence',
    routeIcon: 'help',
    divider: '0',
    hidden: false,
    submenu: [],
  },
  {
    id: 3,
    idModule: 0,
    readWrite: 0,
    routeDescription: 'Map',
    routeLink: '/map',
    routeModule: [1],
    routeTitle: 'Map',
    routeIcon: 'pin_drop',
    divider: '0',
    hidden: false,
    submenu: [],
  },
  {
    id: 3,
    idModule: 0,
    readWrite: 0,
    routeDescription: 'Moyens d\'urgences',
    routeLink: '/departments',
    routeModule: [1],
    routeTitle: 'Moyens d\'urgences',
    routeIcon: 'gavel',
    divider: '0',
    hidden: false,
    submenu: [],
  },
  {
    id: 3,
    idModule: 0,
    readWrite: 0,
    routeDescription: 'Utilisateurs',
    routeLink: '/users',
    routeModule: [1],
    routeTitle: 'Utilisateurs',
    routeIcon: 'person_outline',
    divider: '0',
    hidden: false,
    submenu: [],
  },
  {
    id: 6,
    idModule: 0,
    readWrite: 0,
    routeDescription: 'Paramétrage',
    routeLink: '',
    routeModule: 'subMenu',
    routeTitle: 'Paramétrage',
    routeIcon: 'build',
    divider: '1',
    hidden: false,
    submenu: [
      {
        id: 7,
        idModule: 0,
        readWrite: 1,
        routeDescription: 'Types et Catégories',
        routeLink: '/type-category',
        routeModule: [0],
        routeTitle: 'Types et Catégories',
        routeIcon: '',
        divider: '0',
        submenu: [],
      },
      {
        id: 10,
        idModule: 0,
        readWrite: 0,
        routeDescription: 'Compte',
        routeLink: '/configAccount',
        routeModule: [0],
        routeTitle: 'Compte',
        routeIcon: '',
        divider: '0',
        submenu: [],
      },
    ],
  },
];
